import { LEVELS_NAME } from './levelsName.enum';

export const LOGGER_LEVELS = {
  0: [LEVELS_NAME.LOG],
  1: [LEVELS_NAME.LOG, LEVELS_NAME.ERROR],
  2: [LEVELS_NAME.LOG, LEVELS_NAME.ERROR, LEVELS_NAME.WARN],
  3: [LEVELS_NAME.LOG, LEVELS_NAME.ERROR, LEVELS_NAME.WARN, LEVELS_NAME.DEBUG],
  4: [
    LEVELS_NAME.LOG,
    LEVELS_NAME.ERROR,
    LEVELS_NAME.WARN,
    LEVELS_NAME.DEBUG,
    LEVELS_NAME.VERBOSE,
  ],
};
