version: '3.8'
services:
  app:
    container_name: nestjs-service
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always
    networks:
      - my_network
  postgres:
    container_name: postgres-container
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
